name: JustFlight Bae-146 Bug Report
description: File a bug report
title: "[Bug Bae-146]: "
labels: ["bug", "bae146"]
assignees:
  - theegg52
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for the Yourcontrols profile for the BAE-146!
  - type: input
    id: ycversion
    attributes:
      label: YourControls Version
      description: What Version of YourControls are you using?
    validations:
      required: true
  - type: input
    id: acversion
    attributes:
      label: BAE-146 Version
      description: What Version of the BAE-146 are you using?
    validations:
      required: true
  - type: dropdown
    id: connection
    attributes:
      label: What connection typre were you using
      multiple: true
      options:
        - Cloud P2P
        - Cloud Host
        - Direct
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
