blank_issues_enabled: false
contact_links:
  - name: YourControls Support
    url: https://discord.com/invite/r36d8QAt9Z
    about: For issues with YourContols please joni the Discord and ask the community for help
