name: Duckworks DC-3 Bug Report
description: File a bug report
title: "[Bug DC-3]: "
labels: ["bug", "dc3"]
assignees:
  - theegg52
body:
  - type: input
    id: ycversion
    attributes:
      label: YourControls Version
      description: What Version of YourControls are you using?
    validations:
      required: true
  - type: input
    id: acversion
    attributes:
      label: DC-3 Version
      description: What Version of the DC-3 are you using?
    validations:
      required: true
  - type: dropdown
    id: connection
    attributes:
      label: What connection type were you using?
      multiple: true
      options:
        - Cloud P2P
        - Cloud Host
        - Direct
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output from the YourControls log.
    validations:
      required: false
